/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Familia Silvestre
 */
public class ventanaConvertidor extends javax.swing.JFrame {

    private String divisa1 = "";
    private String divisa2 = "";
    private String cantidad = "";
    private double dinero, cambio;
    private boolean punto = true;

    /**
     * Creates new form ventanaConvertidor
     */
    public ventanaConvertidor() {
        initComponents();
        setSize(300, 450);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panel = new javax.swing.JPanel();
        etiquetaDivisas1 = new javax.swing.JLabel();
        etiquetaCambio1 = new javax.swing.JLabel();
        comboDivisas1 = new javax.swing.JComboBox<>();
        etiquetaDivisas2 = new javax.swing.JLabel();
        etiquetaCambio2 = new javax.swing.JLabel();
        comboDivisas2 = new javax.swing.JComboBox<>();
        panelBoton = new javax.swing.JPanel();
        btnC = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        menuBarra = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        itemCalculadora = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convetidor de moneda");

        panel.setLayout(new java.awt.GridBagLayout());

        etiquetaDivisas1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        etiquetaDivisas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaDivisas1.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panel.add(etiquetaDivisas1, gridBagConstraints);

        etiquetaCambio1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        etiquetaCambio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCambio1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        panel.add(etiquetaCambio1, gridBagConstraints);

        comboDivisas1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboDivisas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoje una divisa", "Estados Unidos - Dolar", "Colombia - COP", "Union Europea - Euro", "Japon - YEN" }));
        comboDivisas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDivisas1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panel.add(comboDivisas1, gridBagConstraints);

        etiquetaDivisas2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        etiquetaDivisas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaDivisas2.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        panel.add(etiquetaDivisas2, gridBagConstraints);

        etiquetaCambio2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        etiquetaCambio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaCambio2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        panel.add(etiquetaCambio2, gridBagConstraints);

        comboDivisas2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboDivisas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoje una divisa", "Estados Unidos - Dolar", "Colombia - COP", "Union Europea - Euro", "Japon - YEN" }));
        comboDivisas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDivisas2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panel.add(comboDivisas2, gridBagConstraints);

        panelBoton.setLayout(new java.awt.GridBagLayout());

        btnC.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btnC, gridBagConstraints);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btnBorrar, gridBagConstraints);

        btn7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btn7, gridBagConstraints);

        btn8.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btn8, gridBagConstraints);

        btn9.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btn9, gridBagConstraints);

        btn4.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btn4, gridBagConstraints);

        btn5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btn5, gridBagConstraints);

        btn6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btn6, gridBagConstraints);

        btn1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btn1, gridBagConstraints);

        btn2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btn2, gridBagConstraints);

        btn3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btn3, gridBagConstraints);

        btn0.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btn0, gridBagConstraints);

        btnPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/punto.png"))); // NOI18N
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        panelBoton.add(btnPunto, gridBagConstraints);

        menu.setText("Usos");
        menu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        itemCalculadora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculadora.png"))); // NOI18N
        itemCalculadora.setText("Calculadora estandar");
        itemCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCalculadoraActionPerformed(evt);
            }
        });
        menu.add(itemCalculadora);
        menu.add(jSeparator1);

        itemSalir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menu.add(itemSalir);

        menuBarra.add(menu);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
            .addComponent(panelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCalculadoraActionPerformed
        VentanaCalculadora calculadora = new VentanaCalculadora();
        calculadora.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemCalculadoraActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void comboDivisas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDivisas1ActionPerformed
        divisa1 = (String) comboDivisas1.getSelectedItem();

        if (divisa1.equals("Estados Unidos - Dolar")) {
            etiquetaDivisas1.setText("$");
        } else if (divisa1.equals("Colombia - COP")) {
            etiquetaDivisas1.setText("$");
        } else if (divisa1.equals("Union Europea - Euro")) {
            etiquetaDivisas1.setText("€");
        } else {
            etiquetaDivisas1.setText("¥");
        }
        obtenerDinero();
    }//GEN-LAST:event_comboDivisas1ActionPerformed

    private void comboDivisas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDivisas2ActionPerformed
        divisa2 = (String) comboDivisas2.getSelectedItem();

        if (divisa2.equals("Estados Unidos - Dolar")) {
            etiquetaDivisas2.setText("$");
        } else if (divisa2.equals("Colombia - COP")) {
            etiquetaDivisas2.setText("$");
        } else if (divisa2.equals("Union Europea - Euro")) {
            etiquetaDivisas2.setText("€");
        } else {
            etiquetaDivisas2.setText("¥");
        }
        obtenerDinero();
    }//GEN-LAST:event_comboDivisas2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (etiquetaCambio1.getText() == "0") {
            cantidad = "1";
        } else {
            cantidad += 1;
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (etiquetaCambio1.getText() == "0") {
            cantidad = "2";
        } else {
            cantidad += 2;
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (etiquetaCambio1.getText() == "0") {
            cantidad = "3";
        } else {
            cantidad += 3;
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (etiquetaCambio1.getText() == "0") {
            cantidad = "4";
        } else {
            cantidad += 4;
        };
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (etiquetaCambio1.getText() == "0") {
            cantidad = "5";
        } else {
            cantidad += 5;
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (etiquetaCambio1.getText() == "0") {
            cantidad = "6";
        } else {
            cantidad += 6;
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (etiquetaCambio1.getText() == "0") {
            cantidad = "7";
        } else {
            cantidad += 7;
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (etiquetaCambio1.getText() == "0") {
            cantidad = "8";
        } else {
            cantidad += 8;
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (etiquetaCambio1.getText() == "0") {
            cantidad = "9";
        } else {
            cantidad += 9;
        }
        etiquetaCambio1.setText(cantidad);
        obtenerDinero();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        if (cantidad != "") {
            cantidad += 0;
            etiquetaCambio1.setText(cantidad);
            obtenerDinero();
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        if (punto) {
            if (cantidad == "") {
                cantidad = "0.";
            } else {
                cantidad += ".";
            }
            etiquetaCambio1.setText(cantidad);
        }
        punto = false;
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int tamaño = cantidad.length();
        if (tamaño > 0) {
            if (tamaño == 1) {
                cantidad = "0";
            } else {
                cantidad = cantidad.substring(0, cantidad.length() - 1);
            }
            etiquetaCambio1.setText(cantidad);
            obtenerDinero();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        cantidad = "";
        punto = true;
        etiquetaCambio1.setText("0");
        etiquetaCambio2.setText("0");
    }//GEN-LAST:event_btnCActionPerformed

    private void obtenerDinero() {
        cantidad = etiquetaCambio1.getText();
        dinero = Double.parseDouble(cantidad);
        System.out.println(dinero);
        convertirDinero();
        dinero *= cambio;
        etiquetaCambio2.setText(String.format("%.2f", dinero));
    }

    private void convertirDinero() {
        if (divisa1.equals(divisa2)) {
            cambio = 1;
        } else if (divisa1.equals("Estados Unidos - Dolar") && divisa2.equals("Colombia - COP")) {
            cambio = 4492;
        } else if (divisa1.equals("Estados Unidos - Dolar") && divisa2.equals("Union Europea - Euro")) {
            cambio = 1.00;
        } else if (divisa1.equals("Estados Unidos - Dolar") && divisa2.equals("Japon - YEN")) {
            cambio = 138.97;
        } else if (divisa1.equals("Colombia - COP") && divisa2.equals("Estados Unidos - Dolar")) {
            cambio = 0.00022;
        } else if (divisa1.equals("Colombia - COP") && divisa2.equals("Union Europea - Euro")) {
            cambio = 0.00022;
        } else if (divisa1.equals("Colombia - COP") && divisa2.equals("Japon - YEN")) {
            cambio = 0.031;
        } else if (divisa1.equals("Union Europea - Euro") && divisa2.equals("Japon - YEN")) {
            cambio = 139.44;
        } else if (divisa1.equals("Union Europea - Euro") && divisa2.equals("Colombia - COP")) {
            cambio = 4507;
        } else if (divisa1.equals("Union Europea - Euro") && divisa2.equals("Estados Unidos - Dolar")) {
            cambio = 1.00;
        } else if (divisa1.equals("Japon - YEN") && divisa2.equals("Estados Unidos - Dolar")) {
            cambio = 0.0072;
        } else if (divisa1.equals("Japon - YEN") && divisa2.equals("Colombia - COP")) {
            cambio = 32.34;
        } else if (divisa1.equals("Japon - YEN") && divisa2.equals("Union Europea - Euro")) {
            cambio = 32.34;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ventanaConvertidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(ventanaConvertidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(ventanaConvertidor.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ventanaConvertidor.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaConvertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnPunto;
    private javax.swing.JComboBox<String> comboDivisas1;
    private javax.swing.JComboBox<String> comboDivisas2;
    private javax.swing.JLabel etiquetaCambio1;
    private javax.swing.JLabel etiquetaCambio2;
    private javax.swing.JLabel etiquetaDivisas1;
    private javax.swing.JLabel etiquetaDivisas2;
    private javax.swing.JMenuItem itemCalculadora;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelBoton;
    // End of variables declaration//GEN-END:variables
}
